ALTER TABLE EQUIPMENT DROP COLUMN tags;
ALTER TABLE MUSCLE DROP COLUMN pics;
ALTER TABLE WORKOUT_PLAN DROP COLUMN cover_url;

DROP TABLE IF EXISTS WORKOUT_PLAN_SET;
DROP TABLE IF EXISTS SUBSCRIPTION_PLAN;
DROP TABLE IF EXISTS COACH_PERMISSION;
DROP TABLE IF EXISTS SUBSCRIPTION_PLAN_COACH_PERMISSION;
DROP TABLE IF EXISTS DISCOUNT_POLICIES;
DROP TABLE IF EXISTS SUBSCRIPTION_PLAN_DISCOUNT_POLICIES;
DROP TABLE IF EXISTS SUBSCRIPTION_ORDER;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS SUBSCRIPTION;
DROP TABLE IF EXISTS QUIZ;
DROP TABLE IF EXISTS PAPER;
DROP TABLE IF EXISTS PAPER_QUIZ;
DROP TABLE IF EXISTS EXAM;
DROP TABLE IF EXISTS QUIZ_ANSWER;
DROP TABLE IF EXISTS COACH_REPORT;
DROP TABLE IF EXISTS COACH_WORKOUT_PLAN_COLLECTION;
DROP TABLE IF EXISTS COACH_WORKOUT_SCHEDULE;

