ALTER TABLE WORKOUT_ACTION ADD COLUMN cover_url TEXT;
ALTER TABLE WORKOUT_DAY ADD COLUMN group_no TEXT;
ALTER TABLE SUBSCRIPTION ADD COLUMN reason TEXT;
ALTER TABLE MEDIA_RESOURCE ADD COLUMN url TEXT;
ALTER TABLE MEDIA_RESOURCE ADD COLUMN cover_key TEXT;
ALTER TABLE MEDIA_RESOURCE ADD COLUMN hash TEXT;
ALTER TABLE MEDIA_RESOURCE ADD COLUMN filename TEXT;
ALTER TABLE MEDIA_RESOURCE ADD COLUMN filetype TEXT;
ALTER TABLE MEDIA_RESOURCE ADD COLUMN creator_id INTEGER;

--礼品码
CREATE TABLE IF NOT EXISTS GIFT_CARD(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL DEFAULT '', --
  status INTEGER NOT NULL DEFAULT 0, --状态 0未使用 1已使用 2已过期 3已作废
  gift_card_reward_id INTEGER NOT NULL DEFAULT 0, --礼品码对应的权益id  一个码对应一个奖励
  consumer_id INTEGER NOT NULL DEFAULT 0, --使用人id
  creator_id INTEGER NOT NULL DEFAULT 0, --创建人id
  d INTEGER,
  used_at DATETIME, --使用时间
  expired_at DATETIME, --失效时间
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 创建时间
);

--礼品码兑换物
CREATE TABLE IF NOT EXISTS GIFT_CARD_REWARD(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL DEFAULT '', --兑换物名称
  overview TEXT NOT NULL DEFAULT '', --兑换物简要说明
  status INTEGER NOT NULL DEFAULT 0, --状态 0 1生效中 2已过期 3已作废
  details TEXT NOT NULL DEFAULT '{}', --using_for 的详细说明
  creator_id INTEGER NOT NULL DEFAULT 0, --创建人id
  d INTEGER,
  expired_at DATETIME, --失效时间
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 创建时间
);
