ALTER TABLE WORKOUT_ACTION DROP COLUMN cover_url;
ALTER TABLE WORKOUT_DAY DROP COLUMN group_no;
ALTER TABLE SUBSCRIPTION DROP COLUMN reason;
ALTER TABLE MEDIA_RESOURCE DROP COLUMN url;
ALTER TABLE MEDIA_RESOURCE DROP COLUMN cover_key;
ALTER TABLE MEDIA_RESOURCE DROP COLUMN hash;
ALTER TABLE MEDIA_RESOURCE DROP COLUMN filename;
ALTER TABLE MEDIA_RESOURCE DROP COLUMN filetype;
ALTER TABLE MEDIA_RESOURCE DROP COLUMN creator_id;
ALTER TABLE COACH DROP COLUMN workout_stats;

DROP TABLE IF EXISTS GIFT_CARD;
DROP TABLE IF EXISTS GIFT_CARD_REWARD;
