ALTER TABLE WORKOUT_PLAN_COLLECTION DROP COLUMN status;
ALTER TABLE WORKOUT_PLAN_COLLECTION DROP COLUMN d;
ALTER TABLE COACH_RELATIONSHIP DROP COLUMN d;


DROP TABLE IF EXISTS INVITATION_CODE;
DROP TABLE IF EXISTS INVITATION_CODE_COACH_RELATION;
