ALTER TABLE COACH ADD COLUMN d INTEGER;
ALTER TABLE WORKOUT_PLAN ADD COLUMN d INTEGER;
ALTER TABLE WORKOUT_DAY ADD COLUMN d INTEGER;
ALTER TABLE WORKOUT_DAY ADD COLUMN medias INTEGER; --训练日 拍照
ALTER TABLE WORKOUT_DAY ADD COLUMN remark INTEGER; --训练日 总结
ALTER TABLE COACH_WORKOUT_PLAN_COLLECTION ADD COLUMN d INTEGER;
ALTER TABLE WORKOUT_PLAN_SET ADD COLUMN d INTEGER;
ALTER TABLE WORKOUT_ACTION_HISTORY ADD COLUMN d INTEGER;
ALTER TABLE WORKOUT_ACTION ADD COLUMN d INTEGER;

ALTER TABLE QUIZ ADD COLUMN d INTEGER;
ALTER TABLE PAPER ADD COLUMN d INTEGER;
ALTER TABLE EXAM ADD COLUMN d INTEGER;

-- 经期记录
CREATE TABLE IF NOT EXISTS MENSTRUAL_CYCLE(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  coach_id INTEGER NOT NULL DEFAULT 0,
  is_cur INTEGER NOT NULL DEFAULT 0, --是否为当前生理周期 0否 1是
  start_date DATETIME, --经期开始时间
  end_date DATETIME, --经期结束时间
  content TEXT NOT NULL DEFAULT '', --备注啥的
  created_at DATETIME --创建时间
);
