ALTER TABLE COACH DROP COLUMN d;
ALTER TABLE WORKOUT_PLAN DROP COLUMN d;
ALTER TABLE WORKOUT_DAY DROP COLUMN d;
ALTER TABLE WORKOUT_DAY DROP COLUMN medias;
ALTER TABLE WORKOUT_DAY DROP COLUMN remark;
ALTER TABLE COACH_WORKOUT_PLAN_COLLECTION DROP COLUMN d;
ALTER TABLE WORKOUT_PLAN_SET DROP COLUMN d;
ALTER TABLE WORKOUT_ACTION_HISTORY DROP COLUMN d;
ALTER TABLE WORKOUT_ACTION DROP COLUMN d;

ALTER TABLE QUIZ DROP COLUMN d;
ALTER TABLE PAPER DROP COLUMN d;
ALTER TABLE EXAM DROP COLUMN d;

DROP TABLE IF EXISTS MENSTRUAL_CYCLE;