DROP TABLE IF EXISTS INFLUENCER;
DROP TABLE IF EXISTS INFLUENCER_PLATFORM;
DROP TABLE IF EXISTS INFLUENCER_ACCOUNT_IN_PLATFORM;
DROP TABLE IF EXISTS COACH_CONTENT;
DROP TABLE IF EXISTS COACH_CONTENT_WITH_WORKOUT_ACTION;
DROP TABLE IF EXISTS COACH_CONTENT_WITH_WORKOUT_PLAN;
DROP TABLE IF EXISTS WORKOUT_OUT_WEEKLY_STATS;
DROP TABLE IF EXISTS NOTIFICATION;