ALTER TABLE COACH_CONTENT_WITH_WORKOUT_PLAN ADD COLUMN status INTEGER; -- 1公开 2私有
ALTER TABLE COACH_CONTENT_WITH_WORKOUT_ACTION ADD COLUMN status INTEGER; -- 1公开 2私有
ALTER TABLE COACH_CONTENT_WITH_WORKOUT_ACTION ADD COLUMN text TEXT; -- 
