ALTER TABLE WORKOUT_PLAN_COLLECTION ADD COLUMN status INTEGER;
ALTER TABLE WORKOUT_PLAN_COLLECTION ADD COLUMN d INTEGER;
ALTER TABLE COACH_RELATIONSHIP ADD COLUMN d INTEGER;

--邀请码
CREATE TABLE IF NOT EXISTS INVITATION_CODE(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL DEFAULT '', --
  status INTEGER NOT NULL DEFAULT 0, --状态 0 1生效中 2已过期 3已作废
  creator_id INTEGER NOT NULL DEFAULT 0, --创建人id
  d INTEGER,
  expired_at DATETIME, --失效时间
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 创建时间
);

--邀请码邀请关系
CREATE TABLE IF NOT EXISTS INVITATION_CODE_COACH_RELATION(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  sc TEXT NOT NULL DEFAULT '', --来源渠道
  inviter_id INTEGER NOT NULL DEFAULT 0, --邀请人id
  invitee_id INTEGER NOT NULL DEFAULT 0, --被邀请人id
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 创建时间
);
