-- Drop tables in reverse order to avoid foreign key constraint issues

DROP TABLE IF EXISTS BODY_MEASUREMENT;
DROP TABLE IF EXISTS WORKOUT_DAY_SET;
DROP TABLE IF EXISTS WORKOUT_DAY;
DROP TABLE IF EXISTS COACH_ACCOUNT;
DROP TABLE IF EXISTS COACH;
DROP TABLE IF EXISTS WORKOUT_DAY_ACTION;
DROP TABLE IF EXISTS WORKOUT_PLAN_ACTION;
DROP TABLE IF EXISTS WORKOUT_PLAN_SET;
DROP TABLE IF EXISTS WORKOUT_PLAN;
DROP TABLE IF EXISTS WORKOUT_ACTION_MISTAKE;
DROP TABLE IF EXISTS MUSCLE;
DROP TABLE IF EXISTS WORKOUT_ACTION;
DROP TABLE IF EXISTS PHYSICAL_TEST;
DROP TABLE IF EXISTS FITNESS_MEMBER;
DROP TABLE IF EXISTS MEDIA_RESOURCE;
DROP TABLE IF EXISTS CHAT_SESSION_AND_LLM_AGENT;
DROP TABLE IF EXISTS CHAT_MEMBER;
DROP TABLE IF EXISTS CHAT_SESSION;
DROP TABLE IF EXISTS CHAT_BOX;
DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS LLM_RESPONSE;
DROP TABLE IF EXISTS LLM_PROVIDER;
DROP TABLE IF EXISTS LLM_PROVIDER_MODEL;
DROP TABLE IF EXISTS LLM_PROVIDER_MODEL_PROFILE;
DROP TABLE IF EXISTS LLM_AGENT;
