
INSERT INTO EQUIPMENT VALUES(1,'dumbbell','哑铃','','哑铃是一种用于增强肌肉力量训练的简单器材，可进行多种部位的力量练习。','{}');
INSERT INTO EQUIPMENT VALUES(2,'barbell','杠铃','','杠铃是举重及健身练习的常见器械，可进行全身性的力量训练。','{}');
INSERT INTO EQUIPMENT VALUES(3,'treadmill','跑步机','','跑步机是家庭及健身房常见的健身器材，是有氧运动的有效工具。','{}');
INSERT INTO EQUIPMENT VALUES(4,'elliptical','椭圆机','','椭圆机是一种全身性的有氧运动器械，对膝关节压力较小。','{}');
INSERT INTO EQUIPMENT VALUES(5,'ab_machine','仰卧板','','仰卧板主要用于腹部等部位的力量训练，辅助进行仰卧起坐等动作。','{}');
INSERT INTO EQUIPMENT VALUES(6,'chest_press_machine','坐姿推胸器','','这是一种固定健身器械，主要用于锻炼胸大肌，通过坐姿推动把手来完成动作，能有效增强胸部力量和维度。','{}');
INSERT INTO EQUIPMENT VALUES(7,'butterfly_machine','蝴蝶机','','专门针对胸肌内侧进行孤立训练的固定器械，模拟蝴蝶展翅动作，可塑造胸部线条。','{}');
INSERT INTO EQUIPMENT VALUES(8,'row_machine','坐姿划船器','','帮助锻炼背部肌群的固定器械，尤其对背阔肌、斜方肌中下束等有很好的刺激效果，增强背部的宽度和厚度。','{}');
INSERT INTO EQUIPMENT VALUES(9,'leg_extension_machine','腿部推蹬机','','主要用于锻炼腿部的大型肌群，如股四头肌、股二头肌和臀大肌等，提供稳定的发力环境来增强腿部力量。','{}');
INSERT INTO EQUIPMENT VALUES(10,'leg_curl_machine','腿部伸展机','','专门针对股四头肌进行锻炼的器械，可有效孤立训练股四头肌，提升其力量和线条。','{}');
INSERT INTO EQUIPMENT VALUES(11,'leg_curl_machine','腿部弯举机','','主要用于锻炼股二头肌，通过弯曲小腿的动作来刺激股二头肌的收缩和生长。','{}');
INSERT INTO EQUIPMENT VALUES(12,'smith_machine','史密斯机','','一种多功能的固定训练器械，具有安全保护装置，可进行深蹲、卧推、硬拉等多种训练动作。','{}');
INSERT INTO EQUIPMENT VALUES(13,'cable_machine','龙门架','','多功能训练设备，可搭配各种配件进行全身各部位的训练，如绳索夹胸、高位下拉、坐姿腿屈伸等动作。','{}');
INSERT INTO EQUIPMENT VALUES(14,'pull_up_machine','引体向上器','','经典的背部训练器械，主要锻炼背阔肌和肱二头肌等，也可辅助进行腹肌训练。','{}');
INSERT INTO EQUIPMENT VALUES(15,'roman_chair','罗马椅','','常用于训练腰背肌和腹肌的器械，可进行罗马椅挺身、仰卧抬腿等动作，增强核心力量。','{}');
INSERT INTO EQUIPMENT VALUES(16,'kettlebell','壶铃','','一种古老的小工具，可用于全身力量、爆发力和协调性训练，常见动作有壶铃摇摆、高脚杯深蹲等。','{}');
INSERT INTO EQUIPMENT VALUES(17,'resistance_band','弹力带','','轻便且多功能的小工具，具有不同的阻力级别，可用于热身、康复训练以及力量辅助训练等，增加训练的多样性。','{}');
INSERT INTO EQUIPMENT VALUES(18,'foam_roller','泡沫轴','','主要用于放松肌肉、缓解肌肉紧张和改善柔韧性的小工具，通过自身重量在泡沫轴上滚动来按摩肌肉。','{}');
INSERT INTO EQUIPMENT VALUES(19,'yoga_ball','瑜伽球','','可用于平衡、核心力量和柔韧性训练的小工具，常见动作有球上平板支撑、仰卧抬腿等。','{}');
INSERT INTO EQUIPMENT VALUES(20,'battle_rope','健身战绳','','一种高强度的训练小工具，通过快速甩动战绳来锻炼手臂、肩部、背部和核心等部位的力量和耐力。','{}');
INSERT INTO EQUIPMENT VALUES(21,'trx_suspension_trainer','TRX悬挂训练带','','利用自身重量进行全身力量、平衡、柔韧性和核心稳定性训练的工具，训练动作丰富多样。','{}');
INSERT INTO EQUIPMENT VALUES(22,'yoga_mat','瑜伽垫','','瑜伽垫是一种用于瑜伽练习的垫子，具有防滑、缓冲和支撑作用，可提供舒适的练习环境。','{}');
INSERT INTO EQUIPMENT VALUES(23,'Hex Bar','六角杠铃','','用于硬拉、农夫行走','');
INSERT INTO EQUIPMENT VALUES(24,'Lat Pulldown Machine','高位下拉机','','高位下拉动作','');
INSERT INTO EQUIPMENT VALUES(25,'Hip Abduction/Adduction Machine','髋外展/内收机','','髋外展和髋内收动作','');
INSERT INTO EQUIPMENT VALUES(26,'Balance Pad','平衡垫','','也叫 波速球，用于稳定性训练，如单腿站立、俯卧撑','');
INSERT INTO EQUIPMENT VALUES(27,'Weight Sled','负重雪橇','','综合性训练，如推雪橇','');
INSERT INTO EQUIPMENT VALUES(28,'Plyo Box','跳箱','','增强式训练，如跳箱、上台阶','');
INSERT INTO EQUIPMENT VALUES(29,'Sandbag','沙袋','','功能性力量训练（搬运、深蹲、过肩抛）','');
INSERT INTO EQUIPMENT VALUES(30,'Climbing Rope','攀爬绳','','上肢拉力和核心稳定性','');
INSERT INTO EQUIPMENT VALUES(31,'Ski Erg','滑雪机','','心肺训练','');
INSERT INTO EQUIPMENT VALUES(32,'Jump Rope','跳绳','','心肺训练','');
INSERT INTO EQUIPMENT VALUES(33,'StairMill','台阶机','','','');
INSERT INTO EQUIPMENT VALUES(34,'VersaClimber','攀爬机','','','');
INSERT INTO EQUIPMENT VALUES(35,'Torso Rotation Machine','旋转核心机','','','');
INSERT INTO EQUIPMENT VALUES(36,'Abdominal Crunch Machine','卷腹机','','','');
INSERT INTO EQUIPMENT VALUES(37,'Standing Calf Raise Machine','站姿提踵机','','','');
INSERT INTO EQUIPMENT VALUES(38,'Seated Calf Raise Machine','坐姿提踵机','','','');
INSERT INTO EQUIPMENT VALUES(39,'Hack Squat Machine','哈克深蹲机','','','');
INSERT INTO EQUIPMENT VALUES(40,'Lateral Raise Machine','侧平举机','','','');
INSERT INTO EQUIPMENT VALUES(41,'T-Bar Row Machine','T 杠划船机','','','');
INSERT INTO EQUIPMENT VALUES(42,'log','圆木','','','');